In [ ]:
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

Mounted at /content/drive


In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.ticker import FormatStrFormatter
import seaborn as sns
sns.set_style(
    style='darkgrid', 
    rc={'axes.facecolor': '.9', 'grid.color': '.8'}
)
#sns.set_palette(palette='deep')
#sns_c = sns.color_palette(palette='deep')
%matplotlib inline
plt.rcParams['figure.figsize'] = [12, 6]
plt.rcParams['figure.dpi'] = 100

In [ ]:
import os
import numpy as np
import matplotlib.pyplot as plt
from imageio import imread
from skimage.transform import resize
import numpy as np
from PIL import Image

In [ ]:
def mass_center(img,is_round=True):
    Y = img.mean(axis=1)
    X = img.mean(axis=0)
    Y_ = np.sum(np.arange(Y.shape[0]) * Y)/np.sum(Y)
    X_ = np.sum(np.arange(X.shape[0]) * X)/np.sum(X)
    if is_round:
        return int(round(X_)),int(round(Y_))
    return X_,Y_

def image_extract(img,newsize):
    x_s = np.where(img.mean(axis=0)!=0)[0].min()
    x_e = np.where(img.mean(axis=0)!=0)[0].max()
    
    y_s = np.where(img.mean(axis=1)!=0)[0].min()
    y_e = np.where(img.mean(axis=1)!=0)[0].max()
    
    x_c,_ = mass_center(img)
    x_s = x_c-newsize[1]//2
    x_e = x_c+newsize[1]//2
    img = img[y_s:y_e,x_s if x_s>0 else 0:x_e if x_e<img.shape[1] else img.shape[1]]
    return np.asarray(Image.fromarray(img).resize(size=newsize).convert('L'))

In [ ]:
from PIL import Image
import imageio

In [ ]:
import tensorflow as tf

In [ ]:
def SSIM_score(y_true, y_pred):
  return tf.image.ssim(y_true, y_pred, max_val=1.0, filter_size=3)

In [ ]:
def SSIM(y_true, y_pred):
  return 1 - tf.reduce_mean(tf.image.ssim(y_true, y_pred, max_val=1.0, filter_size=3))

In [ ]:
X_label = []
k = 0

path = f'/content/drive/MyDrive/GEI_casia/001/'
files = os.listdir(path)
files.sort()
imgs = [imread(path+f) for f in files]
imgs = [image_extract(i,(200,150)) for i in imgs]
imgs = np.minimum(imgs,1)

X = imgs

for _ in range(len(files)):
  X_label.append(k)
k += 1

for id in range(2, 81):
  if id == 5:
    continue
  
  path = f'/content/drive/MyDrive/GEI_casia/{str(id).zfill(3)}/'
  files = os.listdir(path)
  files.sort()
  imgs = [imread(path+f) for f in files]
  imgs = [image_extract(i,(200,150)) for i in imgs]
  imgs = np.minimum(imgs,1)

  X = np.append(X, imgs, 0)

  for _ in range(len(files)):
    X_label.append(k)
  k += 1

<ipython-input-9-818a43545d7f>:7: DeprecationWarning: Starting with ImageIO v3 the behavior of this function will switch to that of iio.v3.imread. To keep the current behavior (and make this warning disappear) use `import imageio.v2 as imageio` or call `imageio.v2.imread` directly.
  imgs = [imread(path+f) for f in files]
<ipython-input-9-818a43545d7f>:24: DeprecationWarning: Starting with ImageIO v3 the behavior of this function will switch to that of iio.v3.imread. To keep the current behavior (and make this warning disappear) use `import imageio.v2 as imageio` or call `imageio.v2.imread` directly.
  imgs = [imread(path+f) for f in files]


In [ ]:
X_label = np.array(X_label)

In [ ]:
label_copy = np.copy(X_label)

In [ ]:
shuffler = np.random.permutation(len(X))

X = X[shuffler]
X_label = X_label[shuffler]

# 10% occlusion

In [ ]:
path = f'/content/drive/MyDrive/GEI_10/000/'
files = os.listdir(path)
files.sort()
imgs = [imread(path+f) for f in files]
imgs = [image_extract(i,(200,150)) for i in imgs]
imgs = np.minimum(imgs,1)

X_10 = imgs

for id in range(1, 79):
  path = f'/content/drive/MyDrive/GEI_10/{str(id).zfill(3)}/'
  files = os.listdir(path)
  files.sort()
  imgs = [imread(path+f) for f in files]
  imgs = [image_extract(i,(200,150)) for i in imgs]
  imgs = np.minimum(imgs,1)

  X_10 = np.append(X_10, imgs, 0)

ssim_10 = []

for i in range(X.shape[0]):
  score = SSIM_score(np.expand_dims(X[i], axis=2), np.expand_dims(X_10[i], axis=2))
  print(score)
  ssim_10.append(score)

<ipython-input-13-cfaecb2722d4>:4: DeprecationWarning: Starting with ImageIO v3 the behavior of this function will switch to that of iio.v3.imread. To keep the current behavior (and make this warning disappear) use `import imageio.v2 as imageio` or call `imageio.v2.imread` directly.
  imgs = [imread(path+f) for f in files]
<ipython-input-13-cfaecb2722d4>:14: DeprecationWarning: Starting with ImageIO v3 the behavior of this function will switch to that of iio.v3.imread. To keep the current behavior (and make this warning disappear) use `import imageio.v2 as imageio` or call `imageio.v2.imread` directly.
  imgs = [imread(path+f) for f in files]


tf.Tensor(0.7090112, shape=(), dtype=float32)
tf.Tensor(0.6546533, shape=(), dtype=float32)
tf.Tensor(0.7153859, shape=(), dtype=float32)
tf.Tensor(0.6480113, shape=(), dtype=float32)
tf.Tensor(0.73825973, shape=(), dtype=float32)
tf.Tensor(0.7045172, shape=(), dtype=float32)
tf.Tensor(0.9077598, shape=(), dtype=float32)
tf.Tensor(0.88912064, shape=(), dtype=float32)
tf.Tensor(0.88751936, shape=(), dtype=float32)
tf.Tensor(0.8809134, shape=(), dtype=float32)
tf.Tensor(0.6546797, shape=(), dtype=float32)
tf.Tensor(0.8911989, shape=(), dtype=float32)
tf.Tensor(0.71889967, shape=(), dtype=float32)
tf.Tensor(0.5591588, shape=(), dtype=float32)
tf.Tensor(0.8617624, shape=(), dtype=float32)
tf.Tensor(0.8176104, shape=(), dtype=float32)
tf.Tensor(0.69721115, shape=(), dtype=float32)
tf.Tensor(0.8730905, shape=(), dtype=float32)
tf.Tensor(0.7266439, shape=(), dtype=float32)
tf.Tensor(0.7328728, shape=(), dtype=float32)
tf.Tensor(0.61432374, shape=(), dtype=float32)
tf.Tensor(0.6371461, shape=(

In [ ]:
sum(ssim_10) / len(ssim_10)

<tf.Tensor: shape=(), dtype=float32, numpy=0.7508856>

# 20% occlusion

In [ ]:
path = f'/content/drive/MyDrive/GEI_20/000/'
files = os.listdir(path)
files.sort()
imgs = [imread(path+f) for f in files]
imgs = [image_extract(i,(200,150)) for i in imgs]
imgs = np.minimum(imgs,1)

X_20 = imgs

for id in range(1, 79):
  path = f'/content/drive/MyDrive/GEI_20/{str(id).zfill(3)}/'
  files = os.listdir(path)
  files.sort()
  imgs = [imread(path+f) for f in files]
  imgs = [image_extract(i,(200,150)) for i in imgs]
  imgs = np.minimum(imgs,1)

  X_20 = np.append(X_20, imgs, 0)

ssim_20 = []

for i in range(X.shape[0]):
  score = SSIM_score(np.expand_dims(X[i], axis=2), np.expand_dims(X_20[i], axis=2))
  print(score)
  ssim_20.append(score)

<ipython-input-15-b0cc03680e0c>:4: DeprecationWarning: Starting with ImageIO v3 the behavior of this function will switch to that of iio.v3.imread. To keep the current behavior (and make this warning disappear) use `import imageio.v2 as imageio` or call `imageio.v2.imread` directly.
  imgs = [imread(path+f) for f in files]
<ipython-input-15-b0cc03680e0c>:14: DeprecationWarning: Starting with ImageIO v3 the behavior of this function will switch to that of iio.v3.imread. To keep the current behavior (and make this warning disappear) use `import imageio.v2 as imageio` or call `imageio.v2.imread` directly.
  imgs = [imread(path+f) for f in files]


tf.Tensor(0.7090112, shape=(), dtype=float32)
tf.Tensor(0.6546533, shape=(), dtype=float32)
tf.Tensor(0.7256378, shape=(), dtype=float32)
tf.Tensor(0.6480113, shape=(), dtype=float32)
tf.Tensor(0.7612239, shape=(), dtype=float32)
tf.Tensor(0.70404226, shape=(), dtype=float32)
tf.Tensor(0.9077598, shape=(), dtype=float32)
tf.Tensor(0.88357896, shape=(), dtype=float32)
tf.Tensor(0.88751936, shape=(), dtype=float32)
tf.Tensor(0.89648205, shape=(), dtype=float32)
tf.Tensor(0.6546117, shape=(), dtype=float32)
tf.Tensor(0.90979105, shape=(), dtype=float32)
tf.Tensor(0.7213595, shape=(), dtype=float32)
tf.Tensor(0.5591588, shape=(), dtype=float32)
tf.Tensor(0.8539763, shape=(), dtype=float32)
tf.Tensor(0.8176104, shape=(), dtype=float32)
tf.Tensor(0.6851263, shape=(), dtype=float32)
tf.Tensor(0.8748912, shape=(), dtype=float32)
tf.Tensor(0.7270184, shape=(), dtype=float32)
tf.Tensor(0.7324039, shape=(), dtype=float32)
tf.Tensor(0.6139152, shape=(), dtype=float32)
tf.Tensor(0.6359366, shape=()

In [ ]:
sum(ssim_20) / len(ssim_20)

<tf.Tensor: shape=(), dtype=float32, numpy=0.74936706>

# 30% occlusion

In [ ]:
path = f'/content/drive/MyDrive/GEI_30/000/'
files = os.listdir(path)
files.sort()
imgs = [imread(path+f) for f in files]
imgs = [image_extract(i,(200,150)) for i in imgs]
imgs = np.minimum(imgs,1)

X_30 = imgs

for id in range(1, 79):
  path = f'/content/drive/MyDrive/GEI_30/{str(id).zfill(3)}/'
  files = os.listdir(path)
  files.sort()
  imgs = [imread(path+f) for f in files]
  imgs = [image_extract(i,(200,150)) for i in imgs]
  imgs = np.minimum(imgs,1)

  X_30 = np.append(X_30, imgs, 0)

ssim_30 = []

for i in range(X.shape[0]):
  score = SSIM_score(np.expand_dims(X[i], axis=2), np.expand_dims(X_30[i], axis=2))
  print(score)
  ssim_30.append(score)

<ipython-input-17-26896cf83c47>:4: DeprecationWarning: Starting with ImageIO v3 the behavior of this function will switch to that of iio.v3.imread. To keep the current behavior (and make this warning disappear) use `import imageio.v2 as imageio` or call `imageio.v2.imread` directly.
  imgs = [imread(path+f) for f in files]
<ipython-input-17-26896cf83c47>:14: DeprecationWarning: Starting with ImageIO v3 the behavior of this function will switch to that of iio.v3.imread. To keep the current behavior (and make this warning disappear) use `import imageio.v2 as imageio` or call `imageio.v2.imread` directly.
  imgs = [imread(path+f) for f in files]


tf.Tensor(0.7012808, shape=(), dtype=float32)
tf.Tensor(0.6516447, shape=(), dtype=float32)
tf.Tensor(0.7425739, shape=(), dtype=float32)
tf.Tensor(0.6512471, shape=(), dtype=float32)
tf.Tensor(0.7951292, shape=(), dtype=float32)
tf.Tensor(0.7102504, shape=(), dtype=float32)
tf.Tensor(0.91201395, shape=(), dtype=float32)
tf.Tensor(0.8748113, shape=(), dtype=float32)
tf.Tensor(0.88751936, shape=(), dtype=float32)
tf.Tensor(0.86159444, shape=(), dtype=float32)
tf.Tensor(0.653381, shape=(), dtype=float32)
tf.Tensor(0.91821164, shape=(), dtype=float32)
tf.Tensor(0.72016376, shape=(), dtype=float32)
tf.Tensor(0.5673934, shape=(), dtype=float32)
tf.Tensor(0.8633032, shape=(), dtype=float32)
tf.Tensor(0.8176104, shape=(), dtype=float32)
tf.Tensor(0.6926919, shape=(), dtype=float32)
tf.Tensor(0.8741541, shape=(), dtype=float32)
tf.Tensor(0.72982925, shape=(), dtype=float32)
tf.Tensor(0.73161745, shape=(), dtype=float32)
tf.Tensor(0.61240584, shape=(), dtype=float32)
tf.Tensor(0.6371027, shape=

In [ ]:
sum(ssim_30) / len(ssim_30)

<tf.Tensor: shape=(), dtype=float32, numpy=0.75033516>

# 40% occlusion

In [ ]:
path = f'/content/drive/MyDrive/GEI_40/000/'
files = os.listdir(path)
files.sort()
imgs = [imread(path+f) for f in files]
imgs = [image_extract(i,(200,150)) for i in imgs]
imgs = np.minimum(imgs,1)

X_40 = imgs

for id in range(1, 79):
  path = f'/content/drive/MyDrive/GEI_40/{str(id).zfill(3)}/'
  files = os.listdir(path)
  files.sort()
  imgs = [imread(path+f) for f in files]
  imgs = [image_extract(i,(200,150)) for i in imgs]
  imgs = np.minimum(imgs,1)

  X_40 = np.append(X_40, imgs, 0)

ssim_40 = []

for i in range(X.shape[0]):
  score = SSIM_score(np.expand_dims(X[i], axis=2), np.expand_dims(X_40[i], axis=2))
  print(score)
  ssim_40.append(score)

<ipython-input-19-7d16f32827b9>:4: DeprecationWarning: Starting with ImageIO v3 the behavior of this function will switch to that of iio.v3.imread. To keep the current behavior (and make this warning disappear) use `import imageio.v2 as imageio` or call `imageio.v2.imread` directly.
  imgs = [imread(path+f) for f in files]
<ipython-input-19-7d16f32827b9>:14: DeprecationWarning: Starting with ImageIO v3 the behavior of this function will switch to that of iio.v3.imread. To keep the current behavior (and make this warning disappear) use `import imageio.v2 as imageio` or call `imageio.v2.imread` directly.
  imgs = [imread(path+f) for f in files]


tf.Tensor(0.7115026, shape=(), dtype=float32)
tf.Tensor(0.64311147, shape=(), dtype=float32)
tf.Tensor(0.74412346, shape=(), dtype=float32)
tf.Tensor(0.6483482, shape=(), dtype=float32)
tf.Tensor(0.82892454, shape=(), dtype=float32)
tf.Tensor(0.7178936, shape=(), dtype=float32)
tf.Tensor(0.91675544, shape=(), dtype=float32)
tf.Tensor(0.8765079, shape=(), dtype=float32)
tf.Tensor(0.8791787, shape=(), dtype=float32)
tf.Tensor(0.8490387, shape=(), dtype=float32)
tf.Tensor(0.6578348, shape=(), dtype=float32)
tf.Tensor(0.9090636, shape=(), dtype=float32)
tf.Tensor(0.7165244, shape=(), dtype=float32)
tf.Tensor(0.567897, shape=(), dtype=float32)
tf.Tensor(0.86004305, shape=(), dtype=float32)
tf.Tensor(0.816856, shape=(), dtype=float32)
tf.Tensor(0.64501876, shape=(), dtype=float32)
tf.Tensor(0.8730698, shape=(), dtype=float32)
tf.Tensor(0.7201123, shape=(), dtype=float32)
tf.Tensor(0.7297871, shape=(), dtype=float32)
tf.Tensor(0.5878603, shape=(), dtype=float32)
tf.Tensor(0.6260007, shape=(),

In [ ]:
sum(ssim_40) / len(ssim_40)

<tf.Tensor: shape=(), dtype=float32, numpy=0.7467741>

# 50% occlusion

In [ ]:
path = f'/content/drive/MyDrive/GEI_50/000/'
files = os.listdir(path)
files.sort()
imgs = [imread(path+f) for f in files]
imgs = [image_extract(i,(200,150)) for i in imgs]
imgs = np.minimum(imgs,1)

X_50 = imgs

for id in range(1, 79):
  path = f'/content/drive/MyDrive/GEI_50/{str(id).zfill(3)}/'
  files = os.listdir(path)
  files.sort()
  imgs = [imread(path+f) for f in files]
  imgs = [image_extract(i,(200,150)) for i in imgs]
  imgs = np.minimum(imgs,1)

  X_50 = np.append(X_50, imgs, 0)

ssim_50 = []

for i in range(X.shape[0]):
  score = SSIM_score(np.expand_dims(X[i], axis=2), np.expand_dims(X_50[i], axis=2))
  print(score)
  ssim_50.append(score)

<ipython-input-21-15fcc30487cb>:4: DeprecationWarning: Starting with ImageIO v3 the behavior of this function will switch to that of iio.v3.imread. To keep the current behavior (and make this warning disappear) use `import imageio.v2 as imageio` or call `imageio.v2.imread` directly.
  imgs = [imread(path+f) for f in files]
<ipython-input-21-15fcc30487cb>:14: DeprecationWarning: Starting with ImageIO v3 the behavior of this function will switch to that of iio.v3.imread. To keep the current behavior (and make this warning disappear) use `import imageio.v2 as imageio` or call `imageio.v2.imread` directly.
  imgs = [imread(path+f) for f in files]


tf.Tensor(0.7217185, shape=(), dtype=float32)
tf.Tensor(0.6256068, shape=(), dtype=float32)
tf.Tensor(0.7400072, shape=(), dtype=float32)
tf.Tensor(0.6424789, shape=(), dtype=float32)
tf.Tensor(0.8182843, shape=(), dtype=float32)
tf.Tensor(0.71320444, shape=(), dtype=float32)
tf.Tensor(0.9130198, shape=(), dtype=float32)
tf.Tensor(0.8975685, shape=(), dtype=float32)
tf.Tensor(0.8784643, shape=(), dtype=float32)
tf.Tensor(0.8829758, shape=(), dtype=float32)
tf.Tensor(0.6650205, shape=(), dtype=float32)
tf.Tensor(0.88855654, shape=(), dtype=float32)
tf.Tensor(0.72322106, shape=(), dtype=float32)
tf.Tensor(0.5593157, shape=(), dtype=float32)
tf.Tensor(0.84763765, shape=(), dtype=float32)
tf.Tensor(0.8152116, shape=(), dtype=float32)
tf.Tensor(0.64845455, shape=(), dtype=float32)
tf.Tensor(0.8729978, shape=(), dtype=float32)
tf.Tensor(0.71681076, shape=(), dtype=float32)
tf.Tensor(0.7347864, shape=(), dtype=float32)
tf.Tensor(0.5906905, shape=(), dtype=float32)
tf.Tensor(0.6244957, shape=(

In [ ]:
sum(ssim_50) / len(ssim_50)

<tf.Tensor: shape=(), dtype=float32, numpy=0.7398981>